// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChdmanService 負責處理 CHD 相關操作，例如解析檔案路徑、Extract CD，以及 Create CD
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateCD 使用 chdman 的 createcd 指令，將 ISO/CUE/BIN 檔案建立成 CHD 檔案
 * 
 * 回傳值：
 *   - string：執行成功後的訊息，例如處理耗時
 *   - error：執行過程中發生的錯誤
 */
export function CreateCD(inputPath: string): $CancellablePromise<string> {
    return $Call.ByID(2256728819, inputPath);
}

/**
 * 使用 chdman 的 extractcd 指令，將 CHD 檔案解開成 CUE/BIN 檔案
 */
export function ExtractCD(inputPath: string): $CancellablePromise<string> {
    return $Call.ByID(1939252694, inputPath);
}

/**
 * ParseFilePath 解析輸入的檔案路徑，並將目錄、檔名與副檔名包裝成 ParseFilePathResult 回傳
 */
export function ParseFilePath(filepath: string): $CancellablePromise<$models.ParseFilePathResult> {
    return $Call.ByID(1747614810, filepath);
}
