// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * 回傳給前端的資料結構
 * 
 * Wails 會將這個 Go struct 轉換成前端可以使用的 JavaScript 物件，因此比直接回傳多個字串更適合用於 Wails binding
 */
export interface ParseFilePathResult {
    /**
     * 檔案所在的目錄
     */
    "dir": string;

    /**
     * 不含副檔名的檔案名稱
     */
    "fileName": string;

    /**
     * 檔案副檔名
     */
    "ext": string;
}
